

export const actionType = {
    SIGN_UP_USER:"SIGN_UP_USER",
    STATE_ALERT:"STATE_ALERT",
    FETCH_SEND_MSG_REQUEST:"FETCH_SEND_MSG_REQUEST",
    FETCH_SEND_MSG_SUCCESS:"FETCH_SEND_MSG_SUCCESS",
    FETCH_SEND_MSG_FAILURE:"FETCH_SEND_MSG_FAILURE",
    FETCH_GET_MSG_REQUEST:"FETCH_GET_MSG_REQUEST",
    FETCH_GET_MSG_SUCCESS:"FETCH_GET_MSG_SUCCESS",
    FETCH_GET_MSG_FAILURE:"FETCH_GET_MSG_FAILURE"
}
